using RestaurantReservation.Services.Helpers;
using RestaurantReservation.Services.SpecialServices;

namespace RestaurantReservation.ConsoleApp.Menus
{
    public class DatabaseFeaturesMenu
    {
        private readonly ViewService _viewService;
        private readonly FunctionService _functionService;
        private readonly StoredProcedureService _storedProcedureService;

        public DatabaseFeaturesMenu(
            ViewService viewService,
            FunctionService functionService,
            StoredProcedureService storedProcedureService)
        {
            _viewService = viewService;
            _functionService = functionService;
            _storedProcedureService = storedProcedureService;
        }

        public void Show()
        {
            Console.Clear();
            Console.WriteLine("Database Features");
            Console.WriteLine("1. Views - All reservations with restaurant and customer details");
            Console.WriteLine("2. Views - All employees with their respective restaurant details");
            Console.WriteLine("3. Functions - Calculate the total revenue generated by a specific restaurant");
            Console.WriteLine("4. Procedures - List all customers who have made reservations with a party size greater than a certain value");
            Console.WriteLine("5. Back to Main Menu");
            Console.Write("Select an option: ");

            var choice = Console.ReadLine();
            switch (choice)
            {
                case "1":
                    _viewService.ViewAllReservationDetails();
                    InputHelper.Continue();
                    break;
                case "2":
                    _viewService.ViewAllEmployeeDetails();
                    InputHelper.Continue();
                    break;
                case "3":
                    _functionService.CalculateRestaurantRevenue();
                    InputHelper.Continue();
                    break;
                case "4":
                    _storedProcedureService.ListAllCusWithMinPartySize();
                    InputHelper.Continue();
                    break;
                case "5":
                    return;
                default:
                    Console.WriteLine("Invalid choice.");
                    InputHelper.Continue();
                    break;
            }
        }
    }
}